language: python
sudo: false
python:
- 3.6
- 3.7-dev
install:
- pip install tox coveralls
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/' | sed
  -e 's/-dev//')
after_success:
- coveralls --verbose
notifications:
  email: false
jobs:
  include:
  - stage: deploy
    deploy:
      provider: pypi
      user: c.tippett
      password:
        secure: D1ebwVd9ngvE5DwzhQ3roELMLuD6vDCv5mU3wh8lMZzr+PU29uPzuyPQem1Y7jRCNJBnSHwYJNeUvK1tzz9sfJnIg5nGs5y3YmzKnd5PgcPRJvD2SQTOcLs7dOSARwC42SAZmOVIn8N1E/5ryctqdrdIceGjZOzAbPRrQNzPeRAKfoGNUMr+wf1n7s9p/w+WVE3aEAtTuJC850IR2/Oo3A55tfPhlE5kp3khDz0HLgHN5tArsOkcr6Hj9KmcM42DZmv1Htqr2w3Jxr/SNXtBtLU7deh6hchKl7IjoF/6+wQKXYra+QkuWLUgxH9ndQpDlRvSKpR4GNvk6aBu4Ww3JQrjy8APHMzFBiQGOdp+WqZx0i5R0dKrsyn4tr4eE70tJSxE4cFmgYQ8AlJFHrFl1Odd3bdslKuM7es4F8QtpDg+h5dn0imPoHM/PWUqcFvAc/P1onAgZ3leEQPT5+oY79UWfQ6JH8Zmnk8AOoRBtvrOYnJXnVHWCrvIzuB9wQqrD1rxIUDoZB12fQeUtax7BOPRp7QHs3D0MJRCqK/SUovSe7JZoObmolv0Tqxn3qg9T/FLqCjzi89sJ5hAsCuxRhmfukllmLkU+ysLp0GbEhnmhz25zFt8Si78tRBeg3jgDYw9xqHsDSVnJu8f3Mkq000+BfB7Ernt57TKrRWfqjk=
      distributions: sdist bdist_wheel
      on:
        tags: true
        branch: master
        repo: christippett/timepro-timesheet
